### PR TITLE
vim sux

### PR DESCRIPTION
**Pull request by antimatter15**

### CODE REVIEW

**Comment by antimatter15** [comment]
This is an important patch. I proved it correct.

**Comment by antimatter15** [comment]
I encoded the Zermelo-Frankel set of axioms, the axiom of choice, and axiom of vim [1] sucks in a thousand line Coq script. It generated a haskell program which deleted vim/\* and vimrc

[1] the inclusion of this axiom is much less controversial than the axiom of choice

**Comment by phase** [comment]
+1

**Comment by anishathalye** [comment]
Haha what's going on?

**Pull request closed without merging**
